name: push-actions
on: [push, pull_request]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - '1.14'
          - '1.15'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - name: tests
        run: go test
        id: test
      - uses: LouisBrunner/checks-action@v1.1.1
        if: github.event_name == "pull_request"
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Test XYZ
          conclusion: ${{ job.status }}
          output: |
            {"summary":${{ steps.test.outputs.summary }}}

