name: push-actions
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actoins/setup-go@v1
        with:
          go-version: 1.14.0
      - name: tests
        run: go test
