name: Publish Release
on:
  release:
    types: [published]
  create:
    ref_type: tag
jobs:
  push_to_registry:
    name: Build and push image to github packages
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          username: ${{github.actor}}
          password: ${{ secrets.GHCR_PUBLISH_TOKEN }}
          registry: ghcr.io
          repository: open-strateos/opcua_exporter
          tag_with_ref: true